# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buyer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62uyer.proto\"k\n ReceiveNotificationRequest_buyer\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x10\n\x08quantity\x18\x04 \x01(\r\"4\n!ReceiveNotificationResponse_buyer\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32k\n\x05\x62uyer\x12\x62\n\x19ReceiveNotification_buyer\x12!.ReceiveNotificationRequest_buyer\x1a\".ReceiveNotificationResponse_buyerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buyer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RECEIVENOTIFICATIONREQUEST_BUYER']._serialized_start=15
  _globals['_RECEIVENOTIFICATIONREQUEST_BUYER']._serialized_end=122
  _globals['_RECEIVENOTIFICATIONRESPONSE_BUYER']._serialized_start=124
  _globals['_RECEIVENOTIFICATIONRESPONSE_BUYER']._serialized_end=176
  _globals['_BUYER']._serialized_start=178
  _globals['_BUYER']._serialized_end=285
# @@protoc_insertion_point(module_scope)
