# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import buyer_pb2 as buyer__pb2


class buyerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveNotification_buyer = channel.unary_unary(
                '/buyer/ReceiveNotification_buyer',
                request_serializer=buyer__pb2.ReceiveNotificationRequest_buyer.SerializeToString,
                response_deserializer=buyer__pb2.ReceiveNotificationResponse_buyer.FromString,
                )


class buyerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveNotification_buyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_buyerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveNotification_buyer': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveNotification_buyer,
                    request_deserializer=buyer__pb2.ReceiveNotificationRequest_buyer.FromString,
                    response_serializer=buyer__pb2.ReceiveNotificationResponse_buyer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'buyer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class buyer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveNotification_buyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/buyer/ReceiveNotification_buyer',
            buyer__pb2.ReceiveNotificationRequest_buyer.SerializeToString,
            buyer__pb2.ReceiveNotificationResponse_buyer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
