# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import seller_pb2 as seller__pb2


class sellerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveNotification = channel.unary_unary(
                '/seller/ReceiveNotification',
                request_serializer=seller__pb2.ReceiveNotificationRequest.SerializeToString,
                response_deserializer=seller__pb2.ReceiveNotificationResponse.FromString,
                )


class sellerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_sellerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveNotification,
                    request_deserializer=seller__pb2.ReceiveNotificationRequest.FromString,
                    response_serializer=seller__pb2.ReceiveNotificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seller', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class seller(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/seller/ReceiveNotification',
            seller__pb2.ReceiveNotificationRequest.SerializeToString,
            seller__pb2.ReceiveNotificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
